// flow-typed signature: 06ecdb45da75464fae39eb6df10441c6
// flow-typed version: <<STUB>>/js-object-pretty-print_v^0.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-object-pretty-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-object-pretty-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'js-object-pretty-print/Gruntfile' {
  declare module.exports: any;
}

declare module 'js-object-pretty-print/index-min' {
  declare module.exports: any;
}

declare module 'js-object-pretty-print/test' {
  declare module.exports: any;
}

declare module 'js-object-pretty-print/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'js-object-pretty-print/Gruntfile.js' {
  declare module.exports: $Exports<'js-object-pretty-print/Gruntfile'>;
}
declare module 'js-object-pretty-print/index-min.js' {
  declare module.exports: $Exports<'js-object-pretty-print/index-min'>;
}
declare module 'js-object-pretty-print/index' {
  declare module.exports: $Exports<'js-object-pretty-print'>;
}
declare module 'js-object-pretty-print/index.js' {
  declare module.exports: $Exports<'js-object-pretty-print'>;
}
declare module 'js-object-pretty-print/test.js' {
  declare module.exports: $Exports<'js-object-pretty-print/test'>;
}
declare module 'js-object-pretty-print/test/index.js' {
  declare module.exports: $Exports<'js-object-pretty-print/test/index'>;
}
